---


- name: load ipmi module
  ignore_errors: yes
  command: kldload ipmi.ko

- name: install libstatgrab
  command: pkg add /opt/check_mk/libstatgrab-0.91.txz

- name: reload filters
  command: /etc/rc.filter_configure
